import java.awt.Color;
import java.awt.Dimension;
import java.awt.EventQueue;
import java.beans.PropertyVetoException;
import javax.swing.JFrame;
import javax.swing.JPanel;
import javax.swing.border.EmptyBorder;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.SwingConstants;
import java.awt.Font;
import javax.swing.JButton;
import javax.swing.ImageIcon;
import javax.swing.JTextField;
import javax.swing.JPasswordField;
import java.awt.event.ActionListener;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.util.Arrays;
import java.util.Random;
import java.awt.event.ActionEvent;
import javax.swing.JComponent;
import javax.swing.border.LineBorder;
public class APadjetivosdemo extends javax.swing.JInternalFrame {
 private JComponent Barra = ((javax.swing.plaf.basic.BasicInternalFrameUI) getUI()).getNorthPane();
	private Dimension dimBarra = null; 
	private JTextField textField;
	private JPasswordField passwordField;
        
        public void ocultarBarraTitulo()
	{ 
	Barra = ((javax.swing.plaf.basic.BasicInternalFrameUI) getUI()).getNorthPane(); 
	dimBarra = Barra.getPreferredSize(); 
	Barra.setSize(0,0); 
	Barra.setPreferredSize(new Dimension(0,0)); 
	repaint(); 
	}
    public APadjetivosdemo() {
        ocultarBarraTitulo();
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel13 = new javax.swing.JPanel();
        jLabel13 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTextArea2 = new javax.swing.JTextArea();

        setBorder(null);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel13.setBackground(new java.awt.Color(0, 153, 153));
        jPanel13.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel13.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(255, 255, 255));
        jLabel13.setText("Adjetivos demostrativos");
        jPanel13.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 0, 230, 60));

        getContentPane().add(jPanel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1170, 60));

        jTextArea2.setEditable(false);
        jTextArea2.setColumns(20);
        jTextArea2.setFont(new java.awt.Font("Arial", 0, 17)); // NOI18N
        jTextArea2.setLineWrap(true);
        jTextArea2.setRows(5);
        jTextArea2.setText("\n\n       1.- Los adjetivos demostrativos son los que muestran o señalan cualquier persona, lugar u objeto (sustantivos).\n\n          Ejemplos:\n\n             •Este libro es barato.\n\n             •Esa falda negra.\n\n       2.- Los adjetivos demostrativos acompañan a los sustantivos y tienen siempre el mismo género (masculino o femenino) y número (singular o plural) \n         que ellos.\n\n         Ejemplos:\n\n             •Ese libro interesante.\n\n             •Esta casa nueva. \n\n       1.- Las formas este, esta y estos se usan para señalar algo que está cerca del hablante. \n\n             •Este lápiz azul.\n\n             •Esta mesa redonda.\n\n             •Estas frutas frescas.\n\n             •Estos zapatos negros.\n\n       2.- Las formas ese, esa, esos y esas se usan para señalar algo que está cerca del que escucha.\n\n             •Ese vaso grande.\n\n             •Esa niña pequeña.\n\n             •Esos juguetes nuevos.\n\n             •Esas voces melodiosas.\n\n       3.- Las formas aquél, aquella, aquellos y aquellas se usan para señalar algo que está lejos del que habla y del que escucha.\n\n             •Aquel día estresante.\n\n             •Aquella tarde tranquila.\n\n             •Aquellos momentos inolvidables.\n\n             •Aquellas canciones románticas.\n\n\n       Observación: Los adjetivos demostrativos sirven también para señalar tiempo.\n \n             •Esta semana comienza mi curso de español. \n  \n             •Esa vez dejo de fumar. \n\n             •Aquellos días de verano fueron fantásticos. \n\n    ___________________________________________________________________________________________________________________________\n\n       Bibliografía: \n   \n       http://ortografía.es.mx\n");
        jTextArea2.setWrapStyleWord(true);
        jTextArea2.setCaretPosition(0);
        jScrollPane2.setViewportView(jTextArea2);

        getContentPane().add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 60, 1170, 590));

        pack();
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel13;
    private javax.swing.JPanel jPanel13;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextArea jTextArea2;
    // End of variables declaration//GEN-END:variables
}
