
import java.awt.Color;
import java.awt.Dimension;
import java.awt.EventQueue;
import java.beans.PropertyVetoException;
import javax.swing.JFrame;
import javax.swing.JPanel;
import javax.swing.border.EmptyBorder;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.SwingConstants;
import java.awt.Font;
import javax.swing.JButton;
import javax.swing.ImageIcon;
import javax.swing.JTextField;
import javax.swing.JPasswordField;
import java.awt.event.ActionListener;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.util.Arrays;
import java.util.Random;
import java.awt.event.ActionEvent;
import javax.swing.JComponent;
import javax.swing.border.LineBorder;

public class DiagnósticoInicial extends javax.swing.JInternalFrame {

    private JComponent Barra = ((javax.swing.plaf.basic.BasicInternalFrameUI) getUI()).getNorthPane();
    private Dimension dimBarra = null;
    private JTextField textField;
    private JPasswordField passwordField;

    public void ocultarBarraTitulo() {
        Barra = ((javax.swing.plaf.basic.BasicInternalFrameUI) getUI()).getNorthPane();
        dimBarra = Barra.getPreferredSize();
        Barra.setSize(0, 0);
        Barra.setPreferredSize(new Dimension(0, 0));
        repaint();
    }

    public DiagnósticoInicial() {
        ocultarBarraTitulo();
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Grupo1 = new javax.swing.ButtonGroup();
        Grupo2 = new javax.swing.ButtonGroup();
        Grupo3 = new javax.swing.ButtonGroup();
        Grupo4 = new javax.swing.ButtonGroup();
        Grupo5 = new javax.swing.ButtonGroup();
        Grupo6 = new javax.swing.ButtonGroup();
        Grupo7 = new javax.swing.ButtonGroup();
        Grupo8 = new javax.swing.ButtonGroup();
        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        buttonGroup3 = new javax.swing.ButtonGroup();
        buttonGroup4 = new javax.swing.ButtonGroup();
        buttonGroup5 = new javax.swing.ButtonGroup();
        buttonGroup6 = new javax.swing.ButtonGroup();
        buttonGroup7 = new javax.swing.ButtonGroup();
        buttonGroup8 = new javax.swing.ButtonGroup();
        buttonGroup9 = new javax.swing.ButtonGroup();
        buttonGroup10 = new javax.swing.ButtonGroup();
        buttonGroup11 = new javax.swing.ButtonGroup();
        buttonGroup12 = new javax.swing.ButtonGroup();
        buttonGroup13 = new javax.swing.ButtonGroup();
        buttonGroup14 = new javax.swing.ButtonGroup();
        buttonGroup15 = new javax.swing.ButtonGroup();
        buttonGroup16 = new javax.swing.ButtonGroup();
        buttonGroup17 = new javax.swing.ButtonGroup();
        buttonGroup18 = new javax.swing.ButtonGroup();
        buttonGroup19 = new javax.swing.ButtonGroup();
        buttonGroup20 = new javax.swing.ButtonGroup();
        buttonGroup21 = new javax.swing.ButtonGroup();
        buttonGroup22 = new javax.swing.ButtonGroup();
        buttonGroup23 = new javax.swing.ButtonGroup();
        buttonGroup24 = new javax.swing.ButtonGroup();
        buttonGroup25 = new javax.swing.ButtonGroup();
        buttonGroup26 = new javax.swing.ButtonGroup();
        buttonGroup27 = new javax.swing.ButtonGroup();
        buttonGroup28 = new javax.swing.ButtonGroup();
        buttonGroup29 = new javax.swing.ButtonGroup();
        buttonGroup30 = new javax.swing.ButtonGroup();
        jPanel13 = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jPanel1 = new javax.swing.JPanel();
        fuentes = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel38 = new javax.swing.JLabel();
        jButton3 = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        cima = new javax.swing.JRadioButton();
        sima = new javax.swing.JRadioButton();
        jLabel6 = new javax.swing.JLabel();
        vaya = new javax.swing.JRadioButton();
        baya = new javax.swing.JRadioButton();
        jLabel9 = new javax.swing.JLabel();
        ajito = new javax.swing.JRadioButton();
        agito = new javax.swing.JRadioButton();
        jLabel11 = new javax.swing.JLabel();
        honda = new javax.swing.JRadioButton();
        onda = new javax.swing.JRadioButton();
        jLabel8 = new javax.swing.JLabel();
        enpírico = new javax.swing.JRadioButton();
        empírico = new javax.swing.JRadioButton();
        jLabel12 = new javax.swing.JLabel();
        quilogramo = new javax.swing.JRadioButton();
        kilogramo = new javax.swing.JRadioButton();
        jLabel13 = new javax.swing.JLabel();
        rrábano = new javax.swing.JRadioButton();
        rábano = new javax.swing.JRadioButton();
        jLabel14 = new javax.swing.JLabel();
        rallado = new javax.swing.JRadioButton();
        rayado = new javax.swing.JRadioButton();
        jLabel16 = new javax.swing.JLabel();
        cima1 = new javax.swing.JRadioButton();
        sima1 = new javax.swing.JRadioButton();
        jLabel17 = new javax.swing.JLabel();
        vaya1 = new javax.swing.JRadioButton();
        baya1 = new javax.swing.JRadioButton();
        ajito1 = new javax.swing.JRadioButton();
        jLabel18 = new javax.swing.JLabel();
        agito1 = new javax.swing.JRadioButton();
        jLabel19 = new javax.swing.JLabel();
        cima2 = new javax.swing.JRadioButton();
        sima2 = new javax.swing.JRadioButton();
        jLabel20 = new javax.swing.JLabel();
        vaya2 = new javax.swing.JRadioButton();
        baya2 = new javax.swing.JRadioButton();
        jButton1 = new javax.swing.JButton();
        jLabel22 = new javax.swing.JLabel();
        cima4 = new javax.swing.JRadioButton();
        sima4 = new javax.swing.JRadioButton();
        jLabel23 = new javax.swing.JLabel();
        vaya3 = new javax.swing.JRadioButton();
        baya3 = new javax.swing.JRadioButton();
        jLabel24 = new javax.swing.JLabel();
        cima3 = new javax.swing.JRadioButton();
        sima3 = new javax.swing.JRadioButton();
        jLabel25 = new javax.swing.JLabel();
        vaya4 = new javax.swing.JRadioButton();
        baya4 = new javax.swing.JRadioButton();
        jLabel21 = new javax.swing.JLabel();
        ajito2 = new javax.swing.JRadioButton();
        agito2 = new javax.swing.JRadioButton();
        jLabel26 = new javax.swing.JLabel();
        honda1 = new javax.swing.JRadioButton();
        onda1 = new javax.swing.JRadioButton();
        jLabel27 = new javax.swing.JLabel();
        enpírico1 = new javax.swing.JRadioButton();
        empírico1 = new javax.swing.JRadioButton();
        jLabel28 = new javax.swing.JLabel();
        quilogramo1 = new javax.swing.JRadioButton();
        kilogramo1 = new javax.swing.JRadioButton();
        jLabel29 = new javax.swing.JLabel();
        rábano1 = new javax.swing.JRadioButton();
        rrábano1 = new javax.swing.JRadioButton();
        jLabel30 = new javax.swing.JLabel();
        rallado1 = new javax.swing.JRadioButton();
        rayado1 = new javax.swing.JRadioButton();
        jLabel31 = new javax.swing.JLabel();
        cima5 = new javax.swing.JRadioButton();
        sima5 = new javax.swing.JRadioButton();
        jLabel32 = new javax.swing.JLabel();
        vaya5 = new javax.swing.JRadioButton();
        baya5 = new javax.swing.JRadioButton();
        jLabel33 = new javax.swing.JLabel();
        ajito3 = new javax.swing.JRadioButton();
        agito3 = new javax.swing.JRadioButton();
        jLabel34 = new javax.swing.JLabel();
        cima6 = new javax.swing.JRadioButton();
        sima6 = new javax.swing.JRadioButton();
        jLabel35 = new javax.swing.JLabel();
        vaya6 = new javax.swing.JRadioButton();
        baya6 = new javax.swing.JRadioButton();
        jLabel36 = new javax.swing.JLabel();
        cima7 = new javax.swing.JRadioButton();
        sima7 = new javax.swing.JRadioButton();
        jLabel37 = new javax.swing.JLabel();
        vaya7 = new javax.swing.JRadioButton();
        baya7 = new javax.swing.JRadioButton();
        jButton2 = new javax.swing.JButton();

        setBackground(new java.awt.Color(255, 255, 255));
        setBorder(null);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel13.setBackground(new java.awt.Color(0, 153, 153));
        jPanel13.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("Examen diagnóstico ");
        jPanel13.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 0, 190, 60));

        jLabel15.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(255, 255, 255));
        jLabel15.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imágenes/Menu.png"))); // NOI18N
        jLabel15.setToolTipText("Menú principal");
        jLabel15.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel15.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jLabel15MousePressed(evt);
            }
        });
        jPanel13.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(1260, 0, 100, 60));

        getContentPane().add(jPanel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1370, -1));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        fuentes.setBackground(new java.awt.Color(255, 255, 255));
        fuentes.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Fuentes consultadas", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 14))); // NOI18N
        fuentes.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setText("  S/N (2016) Curso Propedéutico Lectura, expresión oral y escrita ");
        fuentes.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 150, -1, 30));

        jLabel5.setText("   Mateos, A.. (2009). Ejercicios ortográficos. Naucalpan, Estado de México: Esfinge, S. DE R.L. DE C.V.");
        fuentes.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 50, 460, 30));

        jLabel38.setText("  Aguilar, K.. (2001). Ejercicios de caligrafía, ortografía y redacción. Rep. de Guatemala: Aguilar");
        fuentes.add(jLabel38, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 100, -1, 30));

        jButton3.setBackground(new java.awt.Color(255, 255, 255));
        jButton3.setText("Ok");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        fuentes.add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 230, 70, 40));

        jPanel1.add(fuentes, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 1610, 470, 280));

        jLabel4.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        jLabel4.setText("Selecciona la opción que consideres correcta.");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 60, 350, 30));

        jLabel7.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        jLabel7.setText("1. Su tacto y ama___ilidad son pro___er___iales.");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 140, 450, 30));

        cima.setBackground(new java.awt.Color(255, 255, 255));
        cima.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        cima.setText("b, v, b");
        cima.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        cima.setFocusable(false);
        cima.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cimaActionPerformed(evt);
            }
        });
        jPanel1.add(cima, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 180, 100, -1));

        sima.setBackground(new java.awt.Color(255, 255, 255));
        sima.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        sima.setText("b, v, v");
        sima.setFocusable(false);
        sima.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                simaActionPerformed(evt);
            }
        });
        jPanel1.add(sima, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 220, 100, -1));

        jLabel6.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        jLabel6.setText("2. Fuimos a pre___en___iar cómo  ___arpaba el barco.");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 260, 490, 30));

        vaya.setBackground(new java.awt.Color(255, 255, 255));
        vaya.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        vaya.setText("c, s, z");
        vaya.setFocusable(false);
        vaya.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                vayaActionPerformed(evt);
            }
        });
        jPanel1.add(vaya, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 300, -1, -1));

        baya.setBackground(new java.awt.Color(255, 255, 255));
        baya.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        baya.setText("s, c, z");
        baya.setFocusable(false);
        baya.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bayaActionPerformed(evt);
            }
        });
        jPanel1.add(baya, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 340, -1, -1));

        jLabel9.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        jLabel9.setText("3. Casi me ol___ida___a felicitarlo por su inter___ención.");
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 380, 490, 30));

        ajito.setBackground(new java.awt.Color(255, 255, 255));
        ajito.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        ajito.setText("b, v, b");
        ajito.setFocusable(false);
        jPanel1.add(ajito, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 420, -1, -1));

        agito.setBackground(new java.awt.Color(255, 255, 255));
        agito.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        agito.setText("v, b, v");
        agito.setFocusable(false);
        agito.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                agitoActionPerformed(evt);
            }
        });
        jPanel1.add(agito, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 460, -1, -1));

        jLabel11.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        jLabel11.setText("4. El adorno de la lo___a se destro___ó.");
        jPanel1.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 500, 490, 30));

        honda.setBackground(new java.awt.Color(255, 255, 255));
        honda.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        honda.setText("z, z");
        honda.setFocusable(false);
        jPanel1.add(honda, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 540, -1, -1));

        onda.setBackground(new java.awt.Color(255, 255, 255));
        onda.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        onda.setText("z, s");
        onda.setFocusable(false);
        jPanel1.add(onda, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 580, -1, -1));

        jLabel8.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        jLabel8.setText("5. Caminaré ________ aquella señal");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 610, 450, 30));

        enpírico.setBackground(new java.awt.Color(255, 255, 255));
        enpírico.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        enpírico.setText("asta");
        enpírico.setFocusable(false);
        enpírico.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                enpíricoActionPerformed(evt);
            }
        });
        jPanel1.add(enpírico, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 650, -1, -1));

        empírico.setBackground(new java.awt.Color(255, 255, 255));
        empírico.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        empírico.setText("hasta");
        empírico.setFocusable(false);
        jPanel1.add(empírico, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 690, -1, -1));

        jLabel12.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        jLabel12.setText("6. Lleva más de media hora ____________.");
        jPanel1.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 730, 490, 30));

        quilogramo.setBackground(new java.awt.Color(255, 255, 255));
        quilogramo.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        quilogramo.setText("hablando");
        quilogramo.setFocusable(false);
        quilogramo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                quilogramoActionPerformed(evt);
            }
        });
        jPanel1.add(quilogramo, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 770, -1, -1));

        kilogramo.setBackground(new java.awt.Color(255, 255, 255));
        kilogramo.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        kilogramo.setText("ablando");
        kilogramo.setFocusable(false);
        jPanel1.add(kilogramo, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 810, -1, -1));

        jLabel13.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        jLabel13.setText("7. Voy a _______ el programa, ya que lo televisan muy temprano.");
        jPanel1.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 850, 490, 30));

        rrábano.setBackground(new java.awt.Color(255, 255, 255));
        rrábano.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        rrábano.setText("grabar");
        rrábano.setFocusable(false);
        jPanel1.add(rrábano, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 930, -1, -1));

        rábano.setBackground(new java.awt.Color(255, 255, 255));
        rábano.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        rábano.setText("gravar");
        rábano.setFocusable(false);
        rábano.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rábanoActionPerformed(evt);
            }
        });
        jPanel1.add(rábano, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 890, -1, -1));

        jLabel14.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        jLabel14.setText("8. A donde _______ , llevo mis lentes.");
        jPanel1.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 970, 490, 30));

        rallado.setBackground(new java.awt.Color(255, 255, 255));
        rallado.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        rallado.setText("valla");
        rallado.setFocusable(false);
        jPanel1.add(rallado, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 1010, -1, -1));

        rayado.setBackground(new java.awt.Color(255, 255, 255));
        rayado.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        rayado.setText("vaya");
        rayado.setFocusable(false);
        jPanel1.add(rayado, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 1050, -1, -1));

        jLabel16.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        jLabel16.setText("9.  ¿Qué es una palabra aguda?");
        jPanel1.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 1090, 450, 30));

        cima1.setBackground(new java.awt.Color(255, 255, 255));
        cima1.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        cima1.setText("Aquella que se acentúa en la última sílaba.");
        cima1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        cima1.setFocusable(false);
        cima1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cima1ActionPerformed(evt);
            }
        });
        jPanel1.add(cima1, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 1130, 360, -1));

        sima1.setBackground(new java.awt.Color(255, 255, 255));
        sima1.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        sima1.setText("Aquella que se acentúa en la antepenúltima sílaba.");
        sima1.setFocusable(false);
        sima1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sima1ActionPerformed(evt);
            }
        });
        jPanel1.add(sima1, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 1170, 410, -1));

        jLabel17.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        jLabel17.setText("10. Selecciona la palabra escrita correctamente.");
        jPanel1.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 1210, 490, 30));

        vaya1.setBackground(new java.awt.Color(255, 255, 255));
        vaya1.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        vaya1.setText("corrije");
        vaya1.setFocusable(false);
        vaya1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                vaya1ActionPerformed(evt);
            }
        });
        jPanel1.add(vaya1, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 1250, -1, -1));

        baya1.setBackground(new java.awt.Color(255, 255, 255));
        baya1.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        baya1.setText("corrige");
        baya1.setFocusable(false);
        baya1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                baya1ActionPerformed(evt);
            }
        });
        jPanel1.add(baya1, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 1290, -1, -1));

        ajito1.setBackground(new java.awt.Color(255, 255, 255));
        ajito1.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        ajito1.setText("hierba");
        ajito1.setFocusable(false);
        ajito1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ajito1ActionPerformed(evt);
            }
        });
        jPanel1.add(ajito1, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 1370, -1, -1));

        jLabel18.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        jLabel18.setText("11. Deja que ____________ bien el agua.");
        jPanel1.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 1330, 490, 30));

        agito1.setBackground(new java.awt.Color(255, 255, 255));
        agito1.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        agito1.setText("hierva");
        agito1.setFocusable(false);
        agito1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                agito1ActionPerformed(evt);
            }
        });
        jPanel1.add(agito1, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 1410, -1, -1));

        jLabel19.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        jLabel19.setText("12. Me gusta ______ libro.");
        jPanel1.add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 1440, 450, 30));

        cima2.setBackground(new java.awt.Color(255, 255, 255));
        cima2.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        cima2.setText("mi");
        cima2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        cima2.setFocusable(false);
        cima2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cima2ActionPerformed(evt);
            }
        });
        jPanel1.add(cima2, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 1480, 100, -1));

        sima2.setBackground(new java.awt.Color(255, 255, 255));
        sima2.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        sima2.setText("mí");
        sima2.setFocusable(false);
        sima2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sima2ActionPerformed(evt);
            }
        });
        jPanel1.add(sima2, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 1520, 100, -1));

        jLabel20.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        jLabel20.setText("13. No sabia ______ iba venir a la fiesta.");
        jPanel1.add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 1560, 490, 30));

        vaya2.setBackground(new java.awt.Color(255, 255, 255));
        vaya2.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        vaya2.setText("sí");
        vaya2.setFocusable(false);
        vaya2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                vaya2ActionPerformed(evt);
            }
        });
        jPanel1.add(vaya2, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 1600, -1, -1));

        baya2.setBackground(new java.awt.Color(255, 255, 255));
        baya2.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        baya2.setText("si");
        baya2.setFocusable(false);
        baya2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                baya2ActionPerformed(evt);
            }
        });
        jPanel1.add(baya2, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 1640, -1, -1));

        jButton1.setBackground(new java.awt.Color(255, 255, 255));
        jButton1.setFont(new java.awt.Font("Arial", 1, 15)); // NOI18N
        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imágenes/calificarp.png"))); // NOI18N
        jButton1.setText("Calificar");
        jButton1.setBorder(null);
        jButton1.setBorderPainted(false);
        jButton1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton1.setDisabledIcon(new javax.swing.ImageIcon(getClass().getResource("/Imágenes/calificarp.png"))); // NOI18N
        jButton1.setFocusPainted(false);
        jButton1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton1.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/Imágenes/calificarg.png"))); // NOI18N
        jButton1.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/Imágenes/calificarg.png"))); // NOI18N
        jButton1.setVerticalTextPosition(javax.swing.SwingConstants.TOP);
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 1900, 90, 90));

        jLabel22.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        jLabel22.setText("14. ¿Qué par de palabras son agudas?");
        jPanel1.add(jLabel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 1680, 450, 30));

        cima4.setBackground(new java.awt.Color(255, 255, 255));
        cima4.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        cima4.setText("balón, corazón");
        cima4.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        cima4.setFocusable(false);
        cima4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cima4ActionPerformed(evt);
            }
        });
        jPanel1.add(cima4, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 1720, 150, -1));

        sima4.setBackground(new java.awt.Color(255, 255, 255));
        sima4.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        sima4.setText("corazón, estómago");
        sima4.setFocusable(false);
        sima4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sima4ActionPerformed(evt);
            }
        });
        jPanel1.add(sima4, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 1760, 170, -1));

        jLabel23.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        jLabel23.setText("15. ¿Qué oración hace el uso correcto del acento?");
        jPanel1.add(jLabel23, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 1800, 490, 30));

        vaya3.setBackground(new java.awt.Color(255, 255, 255));
        vaya3.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        vaya3.setText("Aun los niños saben eso.");
        vaya3.setFocusable(false);
        vaya3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                vaya3ActionPerformed(evt);
            }
        });
        jPanel1.add(vaya3, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 1840, -1, -1));

        baya3.setBackground(new java.awt.Color(255, 255, 255));
        baya3.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        baya3.setText("¿No ha llegado aún el cartero?");
        baya3.setFocusable(false);
        baya3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                baya3ActionPerformed(evt);
            }
        });
        jPanel1.add(baya3, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 1880, -1, -1));

        jLabel24.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        jLabel24.setText("16. La coma es utilizada para _______________________.");
        jPanel1.add(jLabel24, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 140, 450, 30));

        cima3.setBackground(new java.awt.Color(255, 255, 255));
        cima3.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        cima3.setText("Separar párrafos.");
        cima3.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        cima3.setFocusable(false);
        cima3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cima3ActionPerformed(evt);
            }
        });
        jPanel1.add(cima3, new org.netbeans.lib.awtextra.AbsoluteConstraints(800, 180, 250, -1));

        sima3.setBackground(new java.awt.Color(255, 255, 255));
        sima3.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        sima3.setText("Separar oraciones breves que van seguidas.");
        sima3.setFocusable(false);
        sima3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sima3ActionPerformed(evt);
            }
        });
        jPanel1.add(sima3, new org.netbeans.lib.awtextra.AbsoluteConstraints(800, 220, 360, -1));

        jLabel25.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        jLabel25.setText("17. Los dos puntos se usan cuando ___________________.");
        jPanel1.add(jLabel25, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 260, 490, 30));

        vaya4.setBackground(new java.awt.Color(255, 255, 255));
        vaya4.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        vaya4.setText("Después de un punto y aparte.");
        vaya4.setFocusable(false);
        vaya4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                vaya4ActionPerformed(evt);
            }
        });
        jPanel1.add(vaya4, new org.netbeans.lib.awtextra.AbsoluteConstraints(800, 300, -1, -1));

        baya4.setBackground(new java.awt.Color(255, 255, 255));
        baya4.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        baya4.setText("Antes de citar textualmente las palabras de otra persona.");
        baya4.setFocusable(false);
        baya4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                baya4ActionPerformed(evt);
            }
        });
        jPanel1.add(baya4, new org.netbeans.lib.awtextra.AbsoluteConstraints(800, 340, -1, -1));

        jLabel21.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        jLabel21.setText("18. Me ofrecieron una taza de ____ .");
        jPanel1.add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 380, 490, 30));

        ajito2.setBackground(new java.awt.Color(255, 255, 255));
        ajito2.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        ajito2.setText("te");
        ajito2.setFocusable(false);
        ajito2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ajito2ActionPerformed(evt);
            }
        });
        jPanel1.add(ajito2, new org.netbeans.lib.awtextra.AbsoluteConstraints(800, 420, -1, -1));

        agito2.setBackground(new java.awt.Color(255, 255, 255));
        agito2.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        agito2.setText("té");
        agito2.setFocusable(false);
        agito2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                agito2ActionPerformed(evt);
            }
        });
        jPanel1.add(agito2, new org.netbeans.lib.awtextra.AbsoluteConstraints(800, 460, -1, -1));

        jLabel26.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        jLabel26.setText("19. Dile que te ______ permiso.");
        jPanel1.add(jLabel26, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 500, 490, 30));

        honda1.setBackground(new java.awt.Color(255, 255, 255));
        honda1.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        honda1.setText("dé");
        honda1.setFocusable(false);
        honda1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                honda1ActionPerformed(evt);
            }
        });
        jPanel1.add(honda1, new org.netbeans.lib.awtextra.AbsoluteConstraints(800, 540, -1, -1));

        onda1.setBackground(new java.awt.Color(255, 255, 255));
        onda1.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        onda1.setText("de");
        onda1.setFocusable(false);
        jPanel1.add(onda1, new org.netbeans.lib.awtextra.AbsoluteConstraints(800, 580, -1, -1));

        jLabel27.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        jLabel27.setText("20. Me vine con _____ a casa.");
        jPanel1.add(jLabel27, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 610, 450, 30));

        enpírico1.setBackground(new java.awt.Color(255, 255, 255));
        enpírico1.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        enpírico1.setText("el");
        enpírico1.setFocusable(false);
        enpírico1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                enpírico1ActionPerformed(evt);
            }
        });
        jPanel1.add(enpírico1, new org.netbeans.lib.awtextra.AbsoluteConstraints(800, 650, -1, -1));

        empírico1.setBackground(new java.awt.Color(255, 255, 255));
        empírico1.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        empírico1.setText("él");
        empírico1.setFocusable(false);
        jPanel1.add(empírico1, new org.netbeans.lib.awtextra.AbsoluteConstraints(800, 690, -1, -1));

        jLabel28.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        jLabel28.setText("21. Me llevaré 4 _ 5 naranjas.");
        jPanel1.add(jLabel28, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 730, 490, 30));

        quilogramo1.setBackground(new java.awt.Color(255, 255, 255));
        quilogramo1.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        quilogramo1.setText("ó");
        quilogramo1.setFocusable(false);
        quilogramo1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                quilogramo1ActionPerformed(evt);
            }
        });
        jPanel1.add(quilogramo1, new org.netbeans.lib.awtextra.AbsoluteConstraints(800, 770, -1, -1));

        kilogramo1.setBackground(new java.awt.Color(255, 255, 255));
        kilogramo1.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        kilogramo1.setText("o");
        kilogramo1.setFocusable(false);
        kilogramo1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                kilogramo1ActionPerformed(evt);
            }
        });
        jPanel1.add(kilogramo1, new org.netbeans.lib.awtextra.AbsoluteConstraints(800, 810, -1, -1));

        jLabel29.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        jLabel29.setText("22. Selecciona el par de palabras escrita correctamente.");
        jPanel1.add(jLabel29, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 850, 490, 30));

        rábano1.setBackground(new java.awt.Color(255, 255, 255));
        rábano1.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        rábano1.setText("corrupcion, relijión");
        rábano1.setFocusable(false);
        rábano1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rábano1ActionPerformed(evt);
            }
        });
        jPanel1.add(rábano1, new org.netbeans.lib.awtextra.AbsoluteConstraints(800, 890, -1, -1));

        rrábano1.setBackground(new java.awt.Color(255, 255, 255));
        rrábano1.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        rrábano1.setText("corrupción, religión.");
        rrábano1.setFocusable(false);
        jPanel1.add(rrábano1, new org.netbeans.lib.awtextra.AbsoluteConstraints(800, 930, -1, -1));

        jLabel30.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        jLabel30.setText("23. Mi padre me llevó a _____________ el fin de semana.");
        jPanel1.add(jLabel30, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 970, 490, 30));

        rallado1.setBackground(new java.awt.Color(255, 255, 255));
        rallado1.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        rallado1.setText("cembrar");
        rallado1.setFocusable(false);
        jPanel1.add(rallado1, new org.netbeans.lib.awtextra.AbsoluteConstraints(800, 1010, -1, -1));

        rayado1.setBackground(new java.awt.Color(255, 255, 255));
        rayado1.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        rayado1.setText("sembrar");
        rayado1.setFocusable(false);
        rayado1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rayado1ActionPerformed(evt);
            }
        });
        jPanel1.add(rayado1, new org.netbeans.lib.awtextra.AbsoluteConstraints(800, 1050, -1, -1));

        jLabel31.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        jLabel31.setText("24. Delante de p, b y n se escribe _______ .");
        jPanel1.add(jLabel31, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 1090, 450, 30));

        cima5.setBackground(new java.awt.Color(255, 255, 255));
        cima5.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        cima5.setText("m");
        cima5.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        cima5.setFocusable(false);
        cima5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cima5ActionPerformed(evt);
            }
        });
        jPanel1.add(cima5, new org.netbeans.lib.awtextra.AbsoluteConstraints(800, 1130, 360, -1));

        sima5.setBackground(new java.awt.Color(255, 255, 255));
        sima5.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        sima5.setText("n");
        sima5.setFocusable(false);
        sima5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sima5ActionPerformed(evt);
            }
        });
        jPanel1.add(sima5, new org.netbeans.lib.awtextra.AbsoluteConstraints(800, 1170, 410, -1));

        jLabel32.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        jLabel32.setText("25. Andres ___ Higinio.");
        jPanel1.add(jLabel32, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 1210, 490, 30));

        vaya5.setBackground(new java.awt.Color(255, 255, 255));
        vaya5.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        vaya5.setText("y");
        vaya5.setFocusable(false);
        vaya5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                vaya5ActionPerformed(evt);
            }
        });
        jPanel1.add(vaya5, new org.netbeans.lib.awtextra.AbsoluteConstraints(800, 1250, -1, -1));

        baya5.setBackground(new java.awt.Color(255, 255, 255));
        baya5.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        baya5.setText("e");
        baya5.setFocusable(false);
        baya5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                baya5ActionPerformed(evt);
            }
        });
        jPanel1.add(baya5, new org.netbeans.lib.awtextra.AbsoluteConstraints(800, 1290, -1, -1));

        jLabel33.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        jLabel33.setText("26. ¿Cómo se le llama a los habitantes de Uruguay?");
        jPanel1.add(jLabel33, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 1330, 490, 30));

        ajito3.setBackground(new java.awt.Color(255, 255, 255));
        ajito3.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        ajito3.setText("uruguayos");
        ajito3.setFocusable(false);
        ajito3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ajito3ActionPerformed(evt);
            }
        });
        jPanel1.add(ajito3, new org.netbeans.lib.awtextra.AbsoluteConstraints(800, 1370, -1, -1));

        agito3.setBackground(new java.awt.Color(255, 255, 255));
        agito3.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        agito3.setText("uruguaios");
        agito3.setFocusable(false);
        agito3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                agito3ActionPerformed(evt);
            }
        });
        jPanel1.add(agito3, new org.netbeans.lib.awtextra.AbsoluteConstraints(800, 1410, -1, -1));

        jLabel34.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        jLabel34.setText("27. Por su ____________ altanera resulta antipático.");
        jPanel1.add(jLabel34, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 1440, 450, 30));

        cima6.setBackground(new java.awt.Color(255, 255, 255));
        cima6.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        cima6.setText("actitud");
        cima6.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        cima6.setFocusable(false);
        cima6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cima6ActionPerformed(evt);
            }
        });
        jPanel1.add(cima6, new org.netbeans.lib.awtextra.AbsoluteConstraints(810, 1480, 100, -1));

        sima6.setBackground(new java.awt.Color(255, 255, 255));
        sima6.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        sima6.setText("aptitud");
        sima6.setFocusable(false);
        sima6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sima6ActionPerformed(evt);
            }
        });
        jPanel1.add(sima6, new org.netbeans.lib.awtextra.AbsoluteConstraints(810, 1520, 100, -1));

        jLabel35.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        jLabel35.setText("28. La _____________ de manos es saludable norma de higiene.");
        jPanel1.add(jLabel35, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 1560, 490, 30));

        vaya6.setBackground(new java.awt.Color(255, 255, 255));
        vaya6.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        vaya6.setText("ablución");
        vaya6.setFocusable(false);
        vaya6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                vaya6ActionPerformed(evt);
            }
        });
        jPanel1.add(vaya6, new org.netbeans.lib.awtextra.AbsoluteConstraints(810, 1600, -1, -1));

        baya6.setBackground(new java.awt.Color(255, 255, 255));
        baya6.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        baya6.setText("ablación");
        baya6.setFocusable(false);
        baya6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                baya6ActionPerformed(evt);
            }
        });
        jPanel1.add(baya6, new org.netbeans.lib.awtextra.AbsoluteConstraints(810, 1640, -1, -1));

        jLabel36.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        jLabel36.setText("29. El vanidoso se procura ___________ cualidades que no tiene.");
        jPanel1.add(jLabel36, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 1680, 480, 30));

        cima7.setBackground(new java.awt.Color(255, 255, 255));
        cima7.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        cima7.setText("arrogar");
        cima7.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        cima7.setFocusable(false);
        cima7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cima7ActionPerformed(evt);
            }
        });
        jPanel1.add(cima7, new org.netbeans.lib.awtextra.AbsoluteConstraints(810, 1720, 150, -1));

        sima7.setBackground(new java.awt.Color(255, 255, 255));
        sima7.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        sima7.setText("abrogar");
        sima7.setFocusable(false);
        sima7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sima7ActionPerformed(evt);
            }
        });
        jPanel1.add(sima7, new org.netbeans.lib.awtextra.AbsoluteConstraints(810, 1760, 170, -1));

        jLabel37.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        jLabel37.setText("30. Eso es lo que yo ___________ en tal caso.");
        jPanel1.add(jLabel37, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 1800, 490, 30));

        vaya7.setBackground(new java.awt.Color(255, 255, 255));
        vaya7.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        vaya7.setText("aria");
        vaya7.setFocusable(false);
        vaya7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                vaya7ActionPerformed(evt);
            }
        });
        jPanel1.add(vaya7, new org.netbeans.lib.awtextra.AbsoluteConstraints(810, 1840, -1, -1));

        baya7.setBackground(new java.awt.Color(255, 255, 255));
        baya7.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        baya7.setText("haría");
        baya7.setFocusable(false);
        baya7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                baya7ActionPerformed(evt);
            }
        });
        jPanel1.add(baya7, new org.netbeans.lib.awtextra.AbsoluteConstraints(810, 1880, -1, -1));

        jButton2.setBackground(new java.awt.Color(255, 255, 255));
        jButton2.setFont(new java.awt.Font("Arial", 1, 15)); // NOI18N
        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imágenes/fuentep.png"))); // NOI18N
        jButton2.setText("Fuentes");
        jButton2.setBorder(null);
        jButton2.setBorderPainted(false);
        jButton2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton2.setDisabledIcon(new javax.swing.ImageIcon(getClass().getResource("/Imágenes/calificarp.png"))); // NOI18N
        jButton2.setFocusPainted(false);
        jButton2.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton2.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/Imágenes/fuenteg.png"))); // NOI18N
        jButton2.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/Imágenes/fuenteg.png"))); // NOI18N
        jButton2.setVerticalTextPosition(javax.swing.SwingConstants.TOP);
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 1900, 90, 90));

        jScrollPane1.setViewportView(jPanel1);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 60, 1370, 610));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jLabel15MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel15MousePressed
       Inicio.logo.setVisible(false);

        Menú abrir = new Menú();
        Inicio.escritorio.add(abrir);
        abrir.toFront();
        abrir.setVisible(true);
//MAXIMIZAR EN TODA LA PANTALLA LOS INTERNALFRAME
        try {
            abrir.setMaximum(true);
        } catch (PropertyVetoException e1) {
            // TODO Auto-generated catch block
            e1.printStackTrace();
        }
    }//GEN-LAST:event_jLabel15MousePressed

    private void cimaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cimaActionPerformed

    }//GEN-LAST:event_cimaActionPerformed

    private void simaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_simaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_simaActionPerformed

    private void vayaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_vayaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_vayaActionPerformed

    private void bayaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bayaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_bayaActionPerformed

    private void agitoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_agitoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_agitoActionPerformed

    private void enpíricoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_enpíricoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_enpíricoActionPerformed

    private void quilogramoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_quilogramoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_quilogramoActionPerformed

    private void rábanoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rábanoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rábanoActionPerformed

    private void cima1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cima1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cima1ActionPerformed

    private void sima1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sima1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_sima1ActionPerformed

    private void vaya1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_vaya1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_vaya1ActionPerformed

    private void baya1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_baya1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_baya1ActionPerformed

    private void ajito1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ajito1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ajito1ActionPerformed

    private void agito1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_agito1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_agito1ActionPerformed

    private void cima2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cima2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cima2ActionPerformed

    private void sima2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sima2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_sima2ActionPerformed

    private void vaya2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_vaya2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_vaya2ActionPerformed

    private void baya2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_baya2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_baya2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed

        if (cima.isSelected() && baya.isSelected() && agito.isSelected() && honda.isSelected() && empírico.isSelected() && kilogramo.isSelected() && rrábano.isSelected() && rayado.isSelected()) {

        }

        // 1
        if (cima.isSelected()) {
            cima.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imágenes/palomita.jpg")));
        } else if (sima.isSelected()) {
            sima.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imágenes/eqis.gif")));
            cima.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imágenes/palomita.jpg")));
        }
        // 2
        if (baya.isSelected()) {
            baya.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imágenes/palomita.jpg")));
        } else if (vaya.isSelected()) {
            vaya.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imágenes/eqis.gif")));
            baya.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imágenes/palomita.jpg")));
        }
        //3
        if (ajito.isSelected()) {
            ajito.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imágenes/eqis.gif")));
            agito.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imágenes/palomita.jpg")));
        } else if (agito.isSelected()) {
            agito.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imágenes/palomita.jpg")));
        }
        //4
        if (honda.isSelected()) {
            honda.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imágenes/palomita.jpg")));
        } else if (onda.isSelected()) {
            onda.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imágenes/eqis.gif")));
            honda.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imágenes/palomita.jpg")));
        }
        //5
        if (enpírico.isSelected()) {
            enpírico.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imágenes/eqis.gif")));
            empírico.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imágenes/palomita.jpg")));
        } else if (empírico.isSelected()) {
            empírico.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imágenes/palomita.jpg")));
        }
        //6
        if (quilogramo.isSelected()) {
            quilogramo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imágenes/palomita.jpg")));
        } else if (kilogramo.isSelected()) {
            quilogramo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imágenes/eqis.gif")));
            kilogramo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imágenes/palomita.jpg")));
        }
        //7
        if (rábano.isSelected()) {
            rábano.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imágenes/eqis.gif")));
            rrábano.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imágenes/palomita.jpg")));
        } else if (rrábano.isSelected()) {
            rrábano.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imágenes/palomita.jpg")));
        }
        //8
        if (rallado.isSelected()) {
            rallado.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imágenes/eqis.gif")));
            rayado.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imágenes/palomita.jpg")));
        } else if (rayado.isSelected()) {
            rayado.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imágenes/palomita.jpg")));
        }
        // 9
        if (cima1.isSelected()) {
            cima1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imágenes/palomita.jpg")));
        } else if (sima1.isSelected()) {
            sima1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imágenes/eqis.gif")));
            cima1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imágenes/palomita.jpg")));
        }
        // 10
        if (baya1.isSelected()) {
            baya1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imágenes/palomita.jpg")));
        } else if (vaya1.isSelected()) {
            vaya1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imágenes/eqis.gif")));
            baya1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imágenes/palomita.jpg")));
        }
        //11
        if (ajito1.isSelected()) {
            ajito1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imágenes/eqis.gif")));
            agito1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imágenes/palomita.jpg")));
        } else if (agito1.isSelected()) {
            agito1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imágenes/palomita.jpg")));
        }
        // 12
        if (cima2.isSelected()) {
            cima2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imágenes/palomita.jpg")));
        } else if (sima2.isSelected()) {
            sima2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imágenes/eqis.gif")));
            cima2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imágenes/palomita.jpg")));
        }
        // 13
        if (baya2.isSelected()) {
            baya2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imágenes/palomita.jpg")));
        } else if (vaya2.isSelected()) {
            vaya2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imágenes/eqis.gif")));
            baya2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imágenes/palomita.jpg")));
        }
        // 14
        if (cima4.isSelected()) {
            cima4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imágenes/palomita.jpg")));
        } else if (sima4.isSelected()) {
            sima4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imágenes/eqis.gif")));
            cima4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imágenes/palomita.jpg")));
        }
        // 15
        if (baya3.isSelected()) {
            baya3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imágenes/palomita.jpg")));
        } else if (vaya3.isSelected()) {
            vaya3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imágenes/eqis.gif")));
            baya3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imágenes/palomita.jpg")));
        }

        // -----------------------------------------------------------------------------------
        // 16
        if (sima3.isSelected()) {
            sima3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imágenes/palomita.jpg")));
        } else if (cima3.isSelected()) {
            cima3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imágenes/eqis.gif")));
            sima3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imágenes/palomita.jpg")));
        }
        // 17
        if (baya4.isSelected()) {
            baya4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imágenes/palomita.jpg")));
        } else if (vaya4.isSelected()) {
            vaya4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imágenes/eqis.gif")));
            baya4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imágenes/palomita.jpg")));
        }
        //18
        if (ajito2.isSelected()) {
            ajito2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imágenes/eqis.gif")));
            agito2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imágenes/palomita.jpg")));
        } else if (agito2.isSelected()) {
            agito2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imágenes/palomita.jpg")));
        }
        //19
        if (honda1.isSelected()) {
            honda1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imágenes/palomita.jpg")));
        } else if (onda1.isSelected()) {
            onda1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imágenes/eqis.gif")));
            honda1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imágenes/palomita.jpg")));
        }
        //20
        if (enpírico1.isSelected()) {
            enpírico1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imágenes/eqis.gif")));
            empírico1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imágenes/palomita.jpg")));
        } else if (empírico1.isSelected()) {
            empírico1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imágenes/palomita.jpg")));
        }
        //21
        if (kilogramo1.isSelected()) {
            kilogramo1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imágenes/palomita.jpg")));
        } else if (quilogramo1.isSelected()) {
            quilogramo1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imágenes/eqis.gif")));
            kilogramo1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imágenes/palomita.jpg")));
        }
        //22
        if (rábano1.isSelected()) {
            rábano1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imágenes/eqis.gif")));
            rrábano1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imágenes/palomita.jpg")));
        } else if (rrábano1.isSelected()) {
            rrábano1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imágenes/palomita.jpg")));
        }
        //23
        if (rallado1.isSelected()) {
            rallado1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imágenes/eqis.gif")));
            rayado1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imágenes/palomita.jpg")));
        } else if (rayado1.isSelected()) {
            rayado1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imágenes/palomita.jpg")));
        }
        //24
        if (cima5.isSelected()) {
            cima5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imágenes/palomita.jpg")));
        } else if (sima5.isSelected()) {
            sima5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imágenes/eqis.gif")));
            cima5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imágenes/palomita.jpg")));
        }
        //25
        if (baya5.isSelected()) {
            baya5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imágenes/palomita.jpg")));
        } else if (vaya5.isSelected()) {
            vaya5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imágenes/eqis.gif")));
            baya5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imágenes/palomita.jpg")));
        }
        //26
        if (agito3.isSelected()) {
            agito3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imágenes/eqis.gif")));
            ajito3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imágenes/palomita.jpg")));
        } else if (ajito3.isSelected()) {
            ajito3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imágenes/palomita.jpg")));
        }
        //27
        if (cima6.isSelected()) {
            cima6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imágenes/palomita.jpg")));
        } else if (sima6.isSelected()) {
            sima6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imágenes/eqis.gif")));
            cima6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imágenes/palomita.jpg")));
        }
        //28
        if (vaya6.isSelected()) {
            vaya6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imágenes/palomita.jpg")));
        } else if (baya6.isSelected()) {
            baya6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imágenes/eqis.gif")));
            vaya6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imágenes/palomita.jpg")));
        }
        //29
        if (cima7.isSelected()) {
            cima7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imágenes/palomita.jpg")));
        } else if (sima7.isSelected()) {
            sima7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imágenes/eqis.gif")));
            cima7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imágenes/palomita.jpg")));
        }
        //30
        if (baya7.isSelected()) {
            baya7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imágenes/palomita.jpg")));
        } else if (vaya7.isSelected()) {
            vaya7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imágenes/eqis.gif")));
            baya7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imágenes/palomita.jpg")));
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void cima4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cima4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cima4ActionPerformed

    private void sima4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sima4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_sima4ActionPerformed

    private void vaya3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_vaya3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_vaya3ActionPerformed

    private void baya3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_baya3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_baya3ActionPerformed

    private void cima3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cima3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cima3ActionPerformed

    private void sima3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sima3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_sima3ActionPerformed

    private void vaya4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_vaya4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_vaya4ActionPerformed

    private void baya4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_baya4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_baya4ActionPerformed

    private void ajito2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ajito2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ajito2ActionPerformed

    private void agito2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_agito2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_agito2ActionPerformed

    private void honda1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_honda1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_honda1ActionPerformed

    private void enpírico1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_enpírico1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_enpírico1ActionPerformed

    private void quilogramo1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_quilogramo1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_quilogramo1ActionPerformed

    private void kilogramo1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_kilogramo1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_kilogramo1ActionPerformed

    private void rábano1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rábano1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rábano1ActionPerformed

    private void rayado1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rayado1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rayado1ActionPerformed

    private void cima5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cima5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cima5ActionPerformed

    private void sima5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sima5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_sima5ActionPerformed

    private void vaya5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_vaya5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_vaya5ActionPerformed

    private void baya5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_baya5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_baya5ActionPerformed

    private void ajito3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ajito3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ajito3ActionPerformed

    private void agito3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_agito3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_agito3ActionPerformed

    private void cima6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cima6ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cima6ActionPerformed

    private void sima6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sima6ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_sima6ActionPerformed

    private void vaya6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_vaya6ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_vaya6ActionPerformed

    private void baya6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_baya6ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_baya6ActionPerformed

    private void cima7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cima7ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cima7ActionPerformed

    private void sima7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sima7ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_sima7ActionPerformed

    private void vaya7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_vaya7ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_vaya7ActionPerformed

    private void baya7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_baya7ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_baya7ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        fuentes.setVisible(false);     // TODO add your handling code here:
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        fuentes.setVisible(true);
    }//GEN-LAST:event_jButton2ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup Grupo1;
    private javax.swing.ButtonGroup Grupo2;
    private javax.swing.ButtonGroup Grupo3;
    private javax.swing.ButtonGroup Grupo4;
    private javax.swing.ButtonGroup Grupo5;
    private javax.swing.ButtonGroup Grupo6;
    private javax.swing.ButtonGroup Grupo7;
    private javax.swing.ButtonGroup Grupo8;
    private javax.swing.JRadioButton agito;
    private javax.swing.JRadioButton agito1;
    private javax.swing.JRadioButton agito2;
    private javax.swing.JRadioButton agito3;
    private javax.swing.JRadioButton ajito;
    private javax.swing.JRadioButton ajito1;
    private javax.swing.JRadioButton ajito2;
    private javax.swing.JRadioButton ajito3;
    private javax.swing.JRadioButton baya;
    private javax.swing.JRadioButton baya1;
    private javax.swing.JRadioButton baya2;
    private javax.swing.JRadioButton baya3;
    private javax.swing.JRadioButton baya4;
    private javax.swing.JRadioButton baya5;
    private javax.swing.JRadioButton baya6;
    private javax.swing.JRadioButton baya7;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup10;
    private javax.swing.ButtonGroup buttonGroup11;
    private javax.swing.ButtonGroup buttonGroup12;
    private javax.swing.ButtonGroup buttonGroup13;
    private javax.swing.ButtonGroup buttonGroup14;
    private javax.swing.ButtonGroup buttonGroup15;
    private javax.swing.ButtonGroup buttonGroup16;
    private javax.swing.ButtonGroup buttonGroup17;
    private javax.swing.ButtonGroup buttonGroup18;
    private javax.swing.ButtonGroup buttonGroup19;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.ButtonGroup buttonGroup20;
    private javax.swing.ButtonGroup buttonGroup21;
    private javax.swing.ButtonGroup buttonGroup22;
    private javax.swing.ButtonGroup buttonGroup23;
    private javax.swing.ButtonGroup buttonGroup24;
    private javax.swing.ButtonGroup buttonGroup25;
    private javax.swing.ButtonGroup buttonGroup26;
    private javax.swing.ButtonGroup buttonGroup27;
    private javax.swing.ButtonGroup buttonGroup28;
    private javax.swing.ButtonGroup buttonGroup29;
    private javax.swing.ButtonGroup buttonGroup3;
    private javax.swing.ButtonGroup buttonGroup30;
    private javax.swing.ButtonGroup buttonGroup4;
    private javax.swing.ButtonGroup buttonGroup5;
    private javax.swing.ButtonGroup buttonGroup6;
    private javax.swing.ButtonGroup buttonGroup7;
    private javax.swing.ButtonGroup buttonGroup8;
    private javax.swing.ButtonGroup buttonGroup9;
    private javax.swing.JRadioButton cima;
    private javax.swing.JRadioButton cima1;
    private javax.swing.JRadioButton cima2;
    private javax.swing.JRadioButton cima3;
    private javax.swing.JRadioButton cima4;
    private javax.swing.JRadioButton cima5;
    private javax.swing.JRadioButton cima6;
    private javax.swing.JRadioButton cima7;
    private javax.swing.JRadioButton empírico;
    private javax.swing.JRadioButton empírico1;
    private javax.swing.JRadioButton enpírico;
    private javax.swing.JRadioButton enpírico1;
    private javax.swing.JPanel fuentes;
    private javax.swing.JRadioButton honda;
    private javax.swing.JRadioButton honda1;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel35;
    private javax.swing.JLabel jLabel36;
    private javax.swing.JLabel jLabel37;
    private javax.swing.JLabel jLabel38;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel13;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JRadioButton kilogramo;
    private javax.swing.JRadioButton kilogramo1;
    private javax.swing.JRadioButton onda;
    private javax.swing.JRadioButton onda1;
    private javax.swing.JRadioButton quilogramo;
    private javax.swing.JRadioButton quilogramo1;
    private javax.swing.JRadioButton rallado;
    private javax.swing.JRadioButton rallado1;
    private javax.swing.JRadioButton rayado;
    private javax.swing.JRadioButton rayado1;
    private javax.swing.JRadioButton rrábano;
    private javax.swing.JRadioButton rrábano1;
    private javax.swing.JRadioButton rábano;
    private javax.swing.JRadioButton rábano1;
    private javax.swing.JRadioButton sima;
    private javax.swing.JRadioButton sima1;
    private javax.swing.JRadioButton sima2;
    private javax.swing.JRadioButton sima3;
    private javax.swing.JRadioButton sima4;
    private javax.swing.JRadioButton sima5;
    private javax.swing.JRadioButton sima6;
    private javax.swing.JRadioButton sima7;
    private javax.swing.JRadioButton vaya;
    private javax.swing.JRadioButton vaya1;
    private javax.swing.JRadioButton vaya2;
    private javax.swing.JRadioButton vaya3;
    private javax.swing.JRadioButton vaya4;
    private javax.swing.JRadioButton vaya5;
    private javax.swing.JRadioButton vaya6;
    private javax.swing.JRadioButton vaya7;
    // End of variables declaration//GEN-END:variables
}
