import com.mysql.jdbc.PreparedStatement;
import java.awt.Dimension;
import java.awt.EventQueue;
import java.beans.PropertyVetoException;
import javax.swing.JFrame;
import javax.swing.JPanel;
import javax.swing.border.EmptyBorder;
import java.awt.Color;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.SwingConstants;
import java.awt.Font;
import java.awt.Image;
import javax.swing.JButton;
import javax.swing.ImageIcon;
import javax.swing.JTextField;
import javax.swing.JPasswordField;
import java.awt.event.ActionListener;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.util.Arrays;
import java.util.Random;
import java.awt.event.ActionEvent;
import java.awt.event.KeyEvent;
import java.io.File;
import java.io.FileInputStream;
import javax.swing.DefaultListModel;
import javax.swing.JComponent;
import javax.swing.JFileChooser;
import javax.swing.border.LineBorder;

public class Diccionario extends javax.swing.JInternalFrame {

    DefaultListModel modelo = new DefaultListModel();

    private JComponent Barra = ((javax.swing.plaf.basic.BasicInternalFrameUI) getUI()).getNorthPane();
    private Dimension dimBarra = null;
    private JTextField textField;
    private JPasswordField passwordField;

    public void ocultarBarraTitulo() {
        Barra = ((javax.swing.plaf.basic.BasicInternalFrameUI) getUI()).getNorthPane();
        dimBarra = Barra.getPreferredSize();
        Barra.setSize(0, 0);
        Barra.setPreferredSize(new Dimension(0, 0));
        repaint();
    }

    public static final String URL = "jdbc:mysql://localhost:3306/administradores?autoReconnect=true&useSSL=false";
    public static final String USERNAME = "root";
    public static final String PASSWORD = "Prototipo19";

    java.sql.PreparedStatement ps;
    ResultSet rs;

    // JAVA-MYsql
    public Connection getConection() {
        Connection con = null;
        try {
            Class.forName("com.mysql.jdbc.Driver");
            con = (Connection) DriverManager.getConnection(URL, USERNAME, PASSWORD);

        } catch (Exception e) {
            System.out.println(e);
        }
        return con;
    }

    public Diccionario() {
        ocultarBarraTitulo();
        initComponents();
        Lista.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        Lista = new javax.swing.JList<>();
        jScrollPane1 = new javax.swing.JScrollPane();
        definición = new javax.swing.JTextArea();
        jPanel13 = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        no = new javax.swing.JTextField();
        GO = new javax.swing.JButton();
        Buscar = new javax.swing.JButton();
        palabra = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setBorder(null);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Lista.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        Lista.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                ListaMousePressed(evt);
            }
        });
        jPanel1.add(Lista, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 180, 990, 100));

        definición.setColumns(20);
        definición.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        definición.setLineWrap(true);
        definición.setRows(5);
        definición.setWrapStyleWord(true);
        jScrollPane1.setViewportView(definición);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 200, 990, 380));

        jPanel13.setBackground(new java.awt.Color(0, 153, 153));
        jPanel13.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("Diccionario");
        jPanel13.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 0, 140, 60));

        jLabel12.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imágenes/Menu.png"))); // NOI18N
        jLabel12.setToolTipText("Menú principal");
        jLabel12.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel12.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jLabel12MousePressed(evt);
            }
        });
        jPanel13.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(1270, 0, 100, 60));

        jPanel1.add(jPanel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1370, -1));

        no.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                noActionPerformed(evt);
            }
        });
        jPanel1.add(no, new org.netbeans.lib.awtextra.AbsoluteConstraints(1260, 160, 80, 30));

        GO.setText("Go");
        GO.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                GOActionPerformed(evt);
            }
        });
        jPanel1.add(GO, new org.netbeans.lib.awtextra.AbsoluteConstraints(1260, 220, 80, 50));

        Buscar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imágenes/lupa.png"))); // NOI18N
        Buscar.setBorder(null);
        Buscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BuscarActionPerformed(evt);
            }
        });
        jPanel1.add(Buscar, new org.netbeans.lib.awtextra.AbsoluteConstraints(1130, 140, -1, -1));

        palabra.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        palabra.setText("acepción");
        palabra.setToolTipText("Buscar");
        palabra.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        palabra.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                palabraActionPerformed(evt);
            }
        });
        palabra.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                palabraKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                palabraKeyReleased(evt);
            }
        });
        jPanel1.add(palabra, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 140, 990, 40));

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jLabel2.setText("La información fue recuperada el 20 de mayo de 2019 http://www.rae.es/recursos/diccionarios");
        jPanel2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 5, -1, 40));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 590, 990, 50));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imágenes/5.jpg"))); // NOI18N
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 60, 1160, 600));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1370, 660));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jLabel12MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel12MousePressed
        Inicio.logo.setVisible(false);
        Inicio.ADiccionario.setVisible(false);
        Inicio.SDiccionario.setVisible(false);

        Menú abrir1 = new Menú();
        Inicio.escritorio.add(abrir1);
        abrir1.toFront();
        abrir1.setVisible(true);
        //MAXIMIZAR EN TODA LA PANTALLA LOS INTERNALFRAME
        try {
            abrir1.setMaximum(true);
        } catch (PropertyVetoException e1) {
            // TODO Auto-generated catch block
            e1.printStackTrace();
        } dispose();
    }//GEN-LAST:event_jLabel12MousePressed

    private void noActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_noActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_noActionPerformed

    private void GOActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_GOActionPerformed
        Connection con = null;
        try {
            con = getConection();
            ps = con.prepareStatement("INSERT INTO diccionario (No, Palabra, Definición) VALUES (?, ?, ?)");
            ps.setString(1, no.getText());
            ps.setString(2, palabra.getText());
            ps.setString(3, definición.getText());

            int res = ps.executeUpdate();
            if (res > 0) {
                JOptionPane.showMessageDialog(null, "Guardado, vamos, vamos, let´s go. ");
            } else {
                JOptionPane.showMessageDialog(null, "error ");
            }

            con.close();
        } catch (Exception e1) {
            System.err.println(e1);
        }
        Inicio.panelLOGOBO.setVisible(true);
        Inicio.jPanel4.setBackground(Color.white);
        Inicio.PanelBotones4.setVisible(false);
        Inicio.btnAcerca.setVisible(false);
        Inicio.btnCrear.setVisible(false);
        Inicio.btnIniciar.setVisible(false);
        // TODO add your handling code here:
    }//GEN-LAST:event_GOActionPerformed

    private void BuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BuscarActionPerformed
        Connection con = null;
        try {
            con = getConection();
            ps = con.prepareStatement("SELECT * FROM diccionario WHERE  palabra= ?");
            ps.setString(1, palabra.getText());
            rs = ps.executeQuery();
            if (rs.next()) {
                definición.setText(rs.getString("Definición"));
            }
        } catch (Exception e) {
            System.err.println(e);
        }
        definición.setEditable(false);
    }//GEN-LAST:event_BuscarActionPerformed

    private void palabraKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_palabraKeyReleased
        Connection con = null;
        con = getConection();
        if (this.palabra.getText().isEmpty())        {
            modelo.clear();
             Lista.setVisible(false);
        }
        else {
            try {
                Class.forName("com.mysql.jdbc.Driver");
                con= DriverManager.getConnection("jdbc:mysql://localhost:3306/administradores?autoReconnect=true&useSSL=false", "root" , "Prototipo19");
                String cad=this.palabra.getText();
                PreparedStatement ps = (PreparedStatement) con.prepareStatement("select palabra FROM diccionario WHERE  palabra like '" + cad + "%'");
                ResultSet rs=ps.executeQuery();
                while (rs.next()) {
                    modelo.addElement(rs.getObject(1));
                }
                  Lista.setVisible(true);
                this.Lista.setModel(modelo);
            } catch (Exception e) {

            }
        }
    }//GEN-LAST:event_palabraKeyReleased

    private void palabraKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_palabraKeyPressed
       
    }//GEN-LAST:event_palabraKeyPressed

    private void palabraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_palabraActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_palabraActionPerformed

    private void ListaMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ListaMousePressed

        Lista.setVisible(false);

    }//GEN-LAST:event_ListaMousePressed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Buscar;
    private javax.swing.JButton GO;
    private javax.swing.JList<String> Lista;
    private javax.swing.JTextArea definición;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel13;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField no;
    private javax.swing.JTextField palabra;
    // End of variables declaration//GEN-END:variables
}
