
import java.awt.Color;
import java.beans.PropertyVetoException;
import java.awt.Color;
import java.beans.PropertyVetoException;
import java.awt.Color;
import java.awt.Dimension;
import java.awt.EventQueue;
import java.beans.PropertyVetoException;
import javax.swing.JFrame;
import javax.swing.JPanel;
import javax.swing.border.EmptyBorder;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.SwingConstants;
import java.awt.Font;
import javax.swing.JButton;
import javax.swing.ImageIcon;
import javax.swing.JTextField;
import javax.swing.JPasswordField;
import java.awt.event.ActionListener;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.util.Arrays;
import java.util.Random;
import java.awt.event.ActionEvent;
import javax.swing.JComponent;
import javax.swing.border.LineBorder;
public class NArtículos extends javax.swing.JInternalFrame {
private JComponent Barra = ((javax.swing.plaf.basic.BasicInternalFrameUI) getUI()).getNorthPane();
	private Dimension dimBarra = null; 
	private JTextField textField;
	private JPasswordField passwordField;
        
        public void ocultarBarraTitulo()
	{ 
	Barra = ((javax.swing.plaf.basic.BasicInternalFrameUI) getUI()).getNorthPane(); 
	dimBarra = Barra.getPreferredSize(); 
	Barra.setSize(0,0); 
	Barra.setPreferredSize(new Dimension(0,0)); 
	repaint(); 
	}
    
    public NArtículos() {
         ocultarBarraTitulo();
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane2 = new javax.swing.JScrollPane();
        jTextArea2 = new javax.swing.JTextArea();
        jPanel13 = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();

        setBorder(null);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTextArea2.setEditable(false);
        jTextArea2.setColumns(20);
        jTextArea2.setFont(new java.awt.Font("Arial", 0, 17)); // NOI18N
        jTextArea2.setLineWrap(true);
        jTextArea2.setRows(5);
        jTextArea2.setText("\n\n       La referencia de un artículo de una revista consta de los siguientes elementos:\n\n              Autor, A. A., Autor, B. B., y Autor, C. C. (Año). Título del artículo. Título de la Revista, xx(x), pp-pp.\n\n       5.1. Autor del artículo.\n  \n              Proceder igual que en los casos de referencia bibliográfica de libros.\n \n       5.2. Año de publicación.\n\n              Indica el año en que se publicó el volumen. Se escribe a continuación del autor separado por un punto y espacio, entre paréntesis.\n\n              Ejemplo: (octubre, 2008)\n \n              Si el volumen abarca más de un año se escriben las fechas que lo abarcan entre paréntesis y separadas por un guión. Ejemplo (1990-1998)\n\n       5.3. Título del artículo.\n \n              Se escribirá con letra común y nunca con cursiva, separado del año de edición mediante punto. Si tiene un subtítulo, se separa del título \n \n              mediante dos puntos.\n\n       5.4. Título de la revista.\n\n              Siempre se escribe en letra cursiva o bien, subrayada. Se separa del título del artículo mediante punto y espacio y va seguido de coma.\n\n       5.5. Volumen, año interno o tomo, y número.\n\n              Se denomina volumen, tomo o año interno a la forma en que el editor de una revista ha dividido esa publicación, puede no coincidir con el año \n\n              calendario. Cada volumen, a su 16 vez, puede separarse en números: divisiones de aparición regular fija (mensual, bimestral, etc.).\n\n              Ejemplo: Año 19 no. 4 se consignará 19(4)\n\n              Aclaración: El volumen se coloca en cursiva y, sin dejar espacio entre ambos, se coloca el número entre paréntesis y sin cursiva. Si la \n\n              Revista no tiene volumen, se escribe el número sin utilizar paréntesis y en cursiva (ver ejemplos 4.7).\n\n       5.6. Paginación.\n \n              Se escriben los números de las páginas abarcadas por el artículo, si se trata de una sola página sólo se coloca un número, si abarca varias \n\n              páginas se separan éstas mediante un guión, las páginas van precedidas por una coma y a continuación va punto final.\n\n       Ejemplos de citas y referencias de artículos de publicaciones periódicas\n\n              Troncoso, G. (1998). Costos en entidades de salud. Costos y Gestión, 30, 93-128. Cita en el texto (Troncoso, 1998, p. 95)\n \n              Gratis es mejor que barato: el CEO de Google y el futuro del negocio. (enero, 2009). Mercado, 1090, 12-14. Cita en el texto\n\n              (“Gratis”, 2009, p. 12)\n\n\n");
        jTextArea2.setWrapStyleWord(true);
        jTextArea2.setCaretPosition(0);
        jScrollPane2.setViewportView(jTextArea2);

        getContentPane().add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 60, 1170, 590));

        jPanel13.setBackground(new java.awt.Color(0, 153, 153));
        jPanel13.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imágenes/Menu.png"))); // NOI18N
        jLabel11.setToolTipText("Menú principal");
        jLabel11.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel11.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jLabel11MousePressed(evt);
            }
        });
        jPanel13.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(1060, 0, 100, 60));

        jLabel12.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setText("Referencias de artículos de revistas");
        jPanel13.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 0, 380, 60));

        getContentPane().add(jPanel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 1, 1170, 60));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jLabel11MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel11MousePressed
        Inicio.logo.setVisible(false);
        Inicio.ANormas.setVisible(false);
        Inicio.SNormas.setVisible(false);

        Menú abrir1 = new Menú();
        Inicio.escritorio.add(abrir1);
        abrir1.toFront();
        abrir1.setVisible(true);
        //MAXIMIZAR EN TODA LA PANTALLA LOS INTERNALFRAME
        try {
            abrir1.setMaximum(true);
        } catch (PropertyVetoException e1) {
            // TODO Auto-generated catch block
            e1.printStackTrace();
        }
    }//GEN-LAST:event_jLabel11MousePressed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JPanel jPanel13;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextArea jTextArea2;
    // End of variables declaration//GEN-END:variables
}
