
import java.awt.Color;
import java.beans.PropertyVetoException;
import java.awt.Color;
import java.beans.PropertyVetoException;
import java.awt.Color;
import java.awt.Dimension;
import java.awt.EventQueue;
import java.beans.PropertyVetoException;
import javax.swing.JFrame;
import javax.swing.JPanel;
import javax.swing.border.EmptyBorder;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.SwingConstants;
import java.awt.Font;
import javax.swing.JButton;
import javax.swing.ImageIcon;
import javax.swing.JTextField;
import javax.swing.JPasswordField;
import java.awt.event.ActionListener;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.util.Arrays;
import java.util.Random;
import java.awt.event.ActionEvent;
import javax.swing.JComponent;
import javax.swing.border.LineBorder;
public class NCitas extends javax.swing.JInternalFrame {
private JComponent Barra = ((javax.swing.plaf.basic.BasicInternalFrameUI) getUI()).getNorthPane();
	private Dimension dimBarra = null; 
	private JTextField textField;
	private JPasswordField passwordField;
        
        public void ocultarBarraTitulo()
	{ 
	Barra = ((javax.swing.plaf.basic.BasicInternalFrameUI) getUI()).getNorthPane(); 
	dimBarra = Barra.getPreferredSize(); 
	Barra.setSize(0,0); 
	Barra.setPreferredSize(new Dimension(0,0)); 
	repaint(); 
	}
    
    public NCitas() {
        ocultarBarraTitulo();
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel13 = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTextArea2 = new javax.swing.JTextArea();

        setBorder(null);

        jPanel13.setBackground(new java.awt.Color(0, 153, 153));
        jPanel13.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imágenes/Menu.png"))); // NOI18N
        jLabel11.setToolTipText("Menú principal");
        jLabel11.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel11.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jLabel11MousePressed(evt);
            }
        });
        jPanel13.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(1060, 0, 100, 60));

        jLabel12.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setText("Citas bibliográficas");
        jPanel13.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 0, 380, 60));

        jTextArea2.setEditable(false);
        jTextArea2.setColumns(20);
        jTextArea2.setFont(new java.awt.Font("Arial", 0, 17)); // NOI18N
        jTextArea2.setLineWrap(true);
        jTextArea2.setRows(5);
        jTextArea2.setText("   \n\n       1.1. Citas textuales\n\n           Todo investigador deberá documentar las opiniones de otros autores mencionados en su trabajo, haciendo referencia a la fuente original. \n\n           Cualquier cita de 40 palabras o menos debe entrecomillarse. Se reemplazan por puntos suspensivos (...) las palabras o frases omitidas. La cita \n\n           textual, se compondrá del apellido del autor, año de la publicación y página/s dedonde se tomó la cita. \n\n           El formato de la cita bibliográfica variará según dónde se coloque el énfasis.\n\n       Enfasis de la cita puesto en el texto: \n\n           El formato de la cita incluirá el texto y al final, entre paréntesis, el apellido del autor, el año de la publicación y la página.\n\n              Ejemplo:\n\n              “Las dos directrices constitucionales que integran el patrimonio cultural son su conservación y difusión, misiones esenciales de los \n\n              memorizadores sociales, como denominó Le Goof a los archiveros y bibliotecarios” (Ramos Simón, 2003, p. 27)\n \n       Y en lista de referencias:\n\n              Ramos Simón, L. F. (coord.). (2003). Impacto de las publicaciones periódicas en las unidades de información. Madrid: Complutense.\n\n       Enfasis de la cita puesto en el autor: El formato de la cita incluirá el apellido del autor, entre paréntesis el año, el contenido del texto y entre \n\n       paréntesis la página de la cual fue tomado.\n\n              Ejemplo:\n\n              Ramos Simón (2003) afirma: “Las bases de datos se configuran como las herramientas más adecuadas y adaptables para la recuperación de \n\n              información yde conocimiento” (p. 69).\n\n       Las citas de más de 40 palabras deben estar separadas del texto comenzando en línea aparte, con una sangría de 5 espacios desde el margen \n\n       izquierdo y sin comillas, se disminuirá el interlineado.\n\n              Ejemplo:\n\n              Keynes (1994) afirma\n\n              El antiguo Egipto era doblemente afortunado, y, sin duda, debió a esto su fabulosa riqueza, porque poseía dos actividades: la de construir \n\n              pirámides y la de buscar metales preciosos cuyos frutos desde el momento que no podían ser útiles para las necesidades humanas, \n\n              consumiéndose, no perdían utilidad por ser abundantes. La edad media construyó catedrales y cantó endechas. Dos pirámides, dos misas de \n\n              réquiem, son dos vecesmejores que una; pero no sucede lo mismo con dos ferrocarriles de Londres a York (p. 122).\n\n       Y en la lista de referencias:\n\n              Keynes, J. M. (1994). Teoría general de la ocupación, el interés y el dinero. Madrid:Planeta. 5\n \n       Enfasis de la cita puesto en el año de publicación: se colocará en primer lugar el año, luego el apellido del autor y la página.\n\n              Ejemplo:\n\n              En 1934, Paul Otlet sostiene “… necesitamos ahora no solamente de bibliografía, descripción de libros, sino de Bibliología, es decir, una \n\n              ciencia y un técnica generales del documento” (p. 9).\n\n       Y en la lista de referencias:\n\n              Otlet, P. (1934). Traité de documentation. Le livre sur le livre: théorie et practique.[Tratado de documentación. El libro sobre el libro: teoría y \n\n             práctica] Brusselles. Editions Mundaneum.\n\n       1.2. Cita parafraseada\n\n       Se denomina cita parafraseada o contextual, cuando se toma la idea de un texto, o se resume, sin utilizar las palabras textuales del autor. En ese \n\n       caso sólo se coloca el año entre paréntesis.\n\n              Ejemplo:\n\n              Ramos Simón (2003) sostiene que uno de los cambios generados por las TIC afecta directamente al tiempo, el cual deja de estar cimentado \n\n              simplemente en el decurso de los días...\n\n       Y en la lista de referencias:\n\n              Ramos Simón, L. F. (coord.). (2003). Impacto de las publicaciones periódicas en las unidades de información. Madrid: Complutense.\n\n       1.3. Citas de segunda mano: Cuando en la cita que se toma hay otra cita, se copia tal cual está y luego se indican los datos de autor y título de la \n \n       obra consultada.\n\n              Ejemplo:\n\n              “... del entierro disputado refleje una específica situación histórica y un conflicto del momento (Steiner, 1991)” (Czernikowski y otros, 2003, p. \n\n              112)\n\n       Y en la lista de referencias\n\n              Czernikowski, E., Gaspari, R., Matus, S. y Moscona, S. (comps.). (2003). Entre hermanos. Buenos Aires: Lugar.\n\n        Aclaración: no se incluirán los datos de Steiner pues la obra consultada fue la de Czernikowski 6\n\n       1.4. Citas en otro idioma: Cuando se utilice una cita en otro idioma ésta debe traducirse, y en la lista de referencias al final del trabajo se incluirá la \n\n       cita completa aclarando que la traducción es del autor del trabajo.\n\n       1.5. Figuras o tablas\n\n       Las tablas o figuras tomadas de un texto y reproducidas fielmente, o adaptadas, deben llevar una nota al pie con información que titule, amplíe o \n\n       explique el contenido de lasmismas y además indique la fuente consultada.\n\n       Si la tabla o figura fue tomada de otra obra, incluir en la nota al pie la referencia completa de la fuente de acuerdo al siguiente formato (esta \n\n       información no se incluye en la lista de referencia del trabajo):\n\n       Publicación periódica: Nota de referencia\n\n       De [o Los datos en la columna son de] “Título del artículo”, por A. A. Autor y B. B. Autor, año, Título de la publicación, Volumen, p. xx. Derechos\n\n       reservados [año] por el Nombre del titular de los derechos de autor.\n\n       Reproducido [o adaptado] con permiso.\n\n       Libro: Nota de referencia\n\n              De [o Adaptado de] Título del libro, (p. xxx), por A. A. Autor y B. B. Autor, año, Lugar de la publicación: Editorial. Derechos reservados [año] por \n              el Nombre del titular de los derechos de autor. Reproducido [o adaptado] con permiso.\n\n              Ejemplo:\n\n              Figura X. Modelo de mediación genérico sujeto a prueba. Adaptado de “Preschool Home Literacy Practices and Children’s Literacy\n\n              Development: A Longitudinal Analysis”, por M. Hood, E. Conlon & G. Andrews, 2008, Journal of Educational Psychology, 100, p. 259. Copyright \n\n              2008 por la American Psychological Association.\n\n              Adaptado de Estrategia competitiva, (p. 67), por M. E. Porter, 2004, México D.F.:\n\n              Compañía Editorial Continental. Copyright 2000 por Grupo Patria Cultural.");
        jTextArea2.setWrapStyleWord(true);
        jTextArea2.setCaretPosition(0);
        jTextArea2.setFocusCycleRoot(true);
        jScrollPane2.setViewportView(jTextArea2);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1170, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 1170, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jPanel13, javax.swing.GroupLayout.PREFERRED_SIZE, 1170, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 654, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                            .addGap(59, 59, 59)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 590, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addComponent(jPanel13, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jLabel11MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel11MousePressed
        Inicio.logo.setVisible(false);
        Inicio.ANormas.setVisible(false);
        Inicio.SNormas.setVisible(false);

        Menú abrir1 = new Menú();
        Inicio.escritorio.add(abrir1);
        abrir1.toFront();
        abrir1.setVisible(true);
        //MAXIMIZAR EN TODA LA PANTALLA LOS INTERNALFRAME
        try {
            abrir1.setMaximum(true);
        } catch (PropertyVetoException e1) {
            // TODO Auto-generated catch block
            e1.printStackTrace();
        }
    }//GEN-LAST:event_jLabel11MousePressed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JPanel jPanel13;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextArea jTextArea2;
    // End of variables declaration//GEN-END:variables
}
